"""Adderror_message to Security Header

Revision ID: 67504c0d3221
Revises: 4cf5ba12a357
Create Date: 2025-01-10 14:27:18.306714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67504c0d3221'
down_revision: Union[str, None] = '4cf5ba12a357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_headers', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('security_headers', 'error_message')
    # ### end Alembic commands ###
